obstacle_range: 2.5
raytrace_range: 3.0 #3.0

footprint: [[-0.18, -0.18], [-0.18, 0.18], [0.18, 0.18], [0.18, -0.18]]
#footprint_padding: 0.008#0.05

#map_topic: map
#subscribe_to_updates: true
#global_frame: odom

#robot_base_frame: base_link
#update_frequency: 30.0
#publish_frequency: 30.0

#max_obstacle_height: 1.0
#min_obstacle_height: 0.05


#robot_radius: 0.18
#inflation_radius: 0.35
cost_scaling_factor: 10.0
map_type: costmap
transform_tolerance: 0.5

plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

#static_layer:
#  map_topic: /map
#  subscribe_to_updates: false

inflation_layer:
  enabled: true             # Whether to apply this plugin or not
  inflation_radius: 0.35     # The radius in meters to which the map inflates obstacle cost values.
  cost_scaling_factor: 10.0 # A scaling factor to apply to cost values during inflation.

obstacle_layer:
  enabled: true
  observation_sources: laser_scan_sensor #point_cloud_sensor

  laser_scan_sensor: {
    sensor_frame: camera_link,
    data_type: LaserScan,
    topic: scan,
    marking: true,
    clearing: true,
    max_obstacle_height: 2.0,
    min_obstacle_height: 0.0, #0.035,
    obstacle_range: 2.5,
    raytrace_range: 3.0,
    inf_is_valid: false
}

static_layer:
  enabled: true
  inflation_radius: 0.45 #0.3

#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
