DWAPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.25 #0.75
  min_vel_x: 0.0 #-0.25

  max_vel_y: 0.0
  min_vel_y: 0.0

# The velocity when robot is moving in a straight line
  max_vel_trans:  0.8
  min_vel_trans:  0.1 #0.13

  max_vel_theta: 1.0 #1.82
  min_vel_theta: -1.0 #0.9

  acc_lim_trans: 0.3
  acc_lim_x: 0.3

  acc_lim_x: 1.8 #2.5
  acc_lim_y: 0.0
  acc_lim_th: 1.8

# Goal Tolerance Parametes
  xy_goal_tolerance: 0.05
  yaw_goal_tolerance: 0.17
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 4.0 # 2.0
  sim_granularity: 0.02 # 0.025 
  vx_samples: 15 #20
  vy_samples: 0
  vth_samples: 20 # 40
  penalize_negative_x: true
  controller_frequency: 10.0

# Trajectory Scoring Parameters
  path_distance_bias: 32.0 # 32.0
  goal_distance_bias: 15.0
  occdist_scale: 0.02
  forward_point_distance: 0 # 0.325
  stop_time_buffer: 1.0 #0.2
  scaling_speed: 0.25
  max_scaling_factor: 10 #0.2
  publish_cost_grid: true

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true

# Global Plan Parameters
  prune_plan: true
