local_costmap:
  global_frame: odom #odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: true #false
  rolling_window: false #true
  width: 6.0
  height: 6.0
  resolution: 0.05
