local_costmap:
  global_frame: odom #odom
  robot_base_frame: base_link

  update_frequency: 5.0 #5.0
  publish_frequency: 10.0 #2.0
  always_send_full_costmap: true 
  transform_tolerance: 0.5 #0.5

  path_distance_bias: 0.95

  # inflation_radius: 0.4
  static_map: false
  rolling_window: true
  
  width: 3.0
  height: 3.0
  resolution: 0.025
  #origin_x: 0.0                   # The x origin of the map in the global frame in meters.
  #origin_y: 0.0                   # The y origin of the map in the global frame in meters.

  #plugins:
  #  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}

  #obstacle_layer:
  #  observation_sources: laser_scan_sensor
  #  laser_scan_sensor: {sensor_frame: camera_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}

#  plugins:
#     - {name: obstacle_layer, type: "costmap_2d::VoxelLayer"}
#     - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
